export const GET_TOKEN = 'GET_TOKEN';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const LOADING_TOKEN = 'REMOVE_TOKEN';
export const ERROR_TOKEN = 'REMOVE_TOKEN';

export const FETCHING_USERS_REQUESTS = 'FETCHING_USERS_REQUEST';
export const FETCHING_USERS_SUCCESS = 'FETCHING_USERS_SUCCESS';
export const FETCHING_USERS_FAILURE = 'FETCHING_USERS_FAILURE';